include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  exclude:
    - .dart_tool/**
    - build/**
    - bench/**
    - bench/*.exe
    - bench/*.csv
    - doc/**
  errors:
    unused_import: error
    dead_code: error
    unused_local_variable: error
    unused_element: error
    always_use_package_imports: error

linter:
  rules:
    - always_use_package_imports
    - avoid_dynamic_calls
    - avoid_redundant_argument_values
    - collection_methods_unrelated_type
    - literal_only_boolean_expressions
    - prefer_final_fields
    - prefer_final_locals
    - prefer_single_quotes
    - unawaited_futures
    - await_only_futures
    - avoid_void_async
    - camel_case_types
    - directives_ordering
    - unnecessary_parenthesis
    - unnecessary_lambdas

